site_name: I dati che Vorrei
site_url: https://vorrei.datibenecomune.it
site_description: Apriamo i dati del PNRR per progettare una società più giusta, inclusiva, collaborativa


repo_url: https://github.com/ondata/i-dati-che-vorrei
repo_name: i-dati-che-vorrei
edit_uri: edit/main/docs/

copyright: 'Un progetto dell''<a href="https://ondata.it/" target="_blank">Associazione onData</a>, cofinanziato da <a href="https://www.opensocietyfoundations.org/" target="_blank">Open Society Foundations</a> | licenza <a rel="license" href="https://creativecommons.org/licenses/by/4.0/deed.it" target="_blank">CC BY 4.0</a>'

theme:
  name: material
  highlightjs: true
  palette:
    - scheme: preference
      primary: black
      accent: orange

  language: it
  favicon: images/favicon.png
#  icon:
#    logo: fontawesome/solid/info-circle
#    logo: ./images/logo.png
  features:
    - navigation.top
#    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.tracking
    - navigation.indexes
  font:
    text: Montserrat
  custom_dir: overrides
  logo: images/logo.svg

# foglio di stile personalizzato
extra_css:
  - stylesheets/style.css

# menu
nav:
  - Home: index.md
  - I dati che vorrei:
    - Perché vogliamo i dati: dati-che-vorrei/index.md
    - Progetti finanziati dal PNRR: dati-che-vorrei/dati.md
    - "Dati: come li vorrei": dati-che-vorrei/come-li-vorrei.md
    - Etica dei dati: dati-che-vorrei/etica-dei-dati.md
    - Glossario: dati-che-vorrei/glossario.md
    - Prossime pubblicazioni:
      - Divario di genere: dati-che-vorrei/prossimamente.md
      - Divario generazionale: dati-che-vorrei/prossimamente.md
      - Divario territoriale: dati-che-vorrei/prossimamente.md
  - Partecipa: partecipa.md
  - Presentazioni: presentazioni.md
  - Crediti: crediti.md
  - DatiBeneComune: https://www.datibenecomune.it/

#extra:
#  social:
#    - icon: material/home
#      link: https://www.datibenecomune.it/
#      name: datiBeneComune

plugins:
- search:
      lang: it
- mkdocstrings
- charts
- tags

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js
  - javascripts/varie.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6

markdown_extensions:
- admonition
- attr_list
- footnotes
- meta
- mkdocs-click
- md_in_html
- pymdownx.betterem:
      smart_enable: all
- pymdownx.caret
#- pyembed.markdown
- pymdownx.critic:
      mode: view
- pymdownx.details
- pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
- pymdownx.highlight
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite
- pymdownx.tabbed:
      alternate_style: true
- pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
- pymdownx.tilde
- toc:
      permalink: true
      toc_depth: 3
- pymdownx.arithmatex:
      generic: true
